version: "1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    # restart: always
    ports:
      - "3307:3306"
    environment:      
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "clienteservidor"

  # docker run -dp 3307:3306 -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=clienteservidor mysql

# CREATE TABLE `libros` (
#   `idLibros` int NOT NULL AUTO_INCREMENT,
#   `autor` varchar(45) DEFAULT NULL,
#   `edicion` varchar(45) DEFAULT NULL,
#   `titulo` varchar(45) DEFAULT NULL,
#   PRIMARY KEY (`idLibros`)
# ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci